blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'
urlpatterns = [
    path('',Blog.as_view(), name = 'blog_index'),
    path('category/<str:category>',BlogArticleCategory.as_view(), name = 'blog_category'),
    path('article/<slug:slug>',BlogArticle.as_view(), name = 'blog_article'),
    path('comment/',Comment.as_view(), name = 'blog_comment'),
    path('search/',search_view, name = 'blog_search'),
    
]

design_y/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from design_y import settings
import web.urls
import blog.urls
import users.urls
from web import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.Index.as_view(), name='landing-page'),
    path('admin/', admin.site.urls),
    path('site/', include(web.urls)),
    path('blog/', include(blog.urls)),
    path('users/', include(users.urls)),
    path('search/', views.search_view, name = 'search'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/reset_done.html'), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/reset_complete.html'), name='password_reset_complete'),
]



if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('edit/', views.edit, name='edit'),
]

web/urls.py
from django.urls import path
import web.views as views

app_name = 'web'
urlpatterns = [
    path('index/', views.Index.as_view(), name = 'web_index'),
    path('product/<slug:slug>', views.ProductDetail.as_view(), name = 'product_detail'),
    path('categories/<str:category>', views.CategoryView.as_view(), name = 'product_categories'),
    path('FAQ/', views.FAQView.as_view(), name = 'qa'),
    path('contact/', views.ContactView.as_view(), name = 'contact'),
    path('new_client/', views.Client.as_view(), name = 'new_client'),
    path('subscribe/', views.SubscribeView.as_view(), name = 'subscribe'),
    path('about/', views.AboutView.as_view(), name = 'about'),
    path('add_to_cart/',views.AddToCart.as_view(), name = 'add_2_cart'),
    path('view_cart_contents/',views.ViewCart.as_view(), name = 'view_cart'),
    path('update_cart/<slug:slug>',views.UpdateCart.as_view(), name = 'update_cart'),
    
    path('checkout/', views.checkout, name="checkout"),
    path('verify_transaction/<str:reference>', views.charge, name="charge"),
    path('my-orders/', views.oderView, name="oderView")
]

blog/models.py
from django.db import models
from web.models import Product
from django.db.models import Q
from django.utils import timezone
from django.conf import settings


# Create your models here.
class Author(models.Model):
	name = models.CharField(max_length = 60)
	photo = models.ImageField(upload_to = 'blog/authors')
	bio = models.TextField()

	def __str__(self):
		return self.name

class Categorie(models.Model):
	categories = (
		('fashion','Fashion'),
		('livestyle','Livestyle'),
		('beauty','Beauty'))
	article_category = models.CharField(max_length = 50, choices = categories)

	def __str__(self):
		return self.article_category
class ArticleQuerySet(models.QuerySet):
    def published(self):
        now = timezone.now()
        return self.filter(upload_date__lte=now)

    def search(self, query):
        lookup = (
                    Q(title__icontains=query) |
                    Q(slug__icontains=query) |
                    Q(author__name__icontains=query) |
                    Q(author__bio__icontains=query)
                    )

        return self.filter(lookup)


class ArticleManager(models.Manager):
    def get_queryset(self):
        return ArticleQuerySet(self.model, using=self._db)

    def published(self):
        return self.get_queryset().published()

    def search(self, query=None):
        if query is None:
            return self.get_queryset().none()
        return self.get_queryset().published().search(query)

class Article(models.Model):
	p_status = (
		('publish','Publish'),
		('draft','Draft'))
	author = models.ForeignKey(Author, on_delete = models.SET_NULL, null = True)
	title = models.CharField(max_length = 200)
	categories = models.ManyToManyField(Categorie)
	featured_products = models.ManyToManyField(Product, blank = True)
	publication_status = models.CharField(max_length = 60, choices = p_status)
	slug = models.SlugField()
	upload_date = models.DateTimeField()

	objects = ArticleManager()

	def __str__(self):
		return self.title

class ArticleText(models.Model):
	article = models.ForeignKey(Article, on_delete = models.CASCADE)
	header = models.CharField(max_length = 200, blank = True)
	text = models.TextField()

	def __str__(self):
		return self.article.title

class ArticleImage(models.Model):
	article = models.ForeignKey(Article, on_delete = models.CASCADE)
	caption = models.CharField(max_length = 200, blank = True)
	image_file = models.ImageField(upload_to = 'blog/articles/images')

	def __str__(self):
		return self.article.title

class ArticleVideo(models.Model):
	article = models.ForeignKey(Article, on_delete = models.CASCADE)
	caption = models.CharField(max_length = 200, blank = True)
	video_file = models.FileField(upload_to = 'blog/articles/videos')

	def __str__(self):
		return self.article.title

class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete = models.CASCADE)
	comment = models.TextField()
	name = models.CharField(max_length = 50)
	email = models.EmailField()
	website = models.URLField(blank = True)
	upload_timestamp = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return self.name

web/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings
from django.db.models import Q
from django.utils import timezone
from django.forms import ModelForm

# Get the user model
User = get_user_model()

# Create your models here.

class SiteDetail(models.Model):
    name = models.CharField(max_length = 100)
    logo = models.ImageField(upload_to = 'site_detail/images')
    favicon = models.ImageField(upload_to = 'site_detail/images')
    apple_icon = models.ImageField(upload_to = 'site_detail/images')
    address = models.TextField()
    site_email = models.EmailField()
    site_biography = models.TextField()
    site_mission = models.TextField()
    site_quote = models.TextField()
    site_quote_by = models.TextField()
    our_story_image = models.ImageField(upload_to = 'site_detail/images', blank = True)
    our_mission_image = models.ImageField(upload_to = 'site_detail/images', blank = True)

    def __str__(self):
        return self.name

class PhoneNumber(models.Model):
    name = models.CharField(max_length = 70)
    phone_number = models.CharField(max_length = 14)
    site = models.ForeignKey(SiteDetail, on_delete = models.CASCADE)

    def __str__(self):
        return self.name

class SiteSocial(models.Model):
    socials = (
        ('facebook','Facebook'),
        ('instagram','Instagram'),
        ('twitter','Twitter'),
        ('whatsapp','WhatsAap'))
    site = models.ForeignKey(SiteDetail, on_delete = models.CASCADE)
    social_media = models.CharField(max_length = 50, choices = socials)
    link = models.URLField()

    def __str__(self):
        return self.social_media

class Categorie(models.Model):
    name = models.CharField(max_length = 40)
    image = models.ImageField(upload_to = 'category/images')
    slug = models.SlugField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

class ProductQuerySet(models.QuerySet):

    def search(self, query):
        lookup = (
                    Q(name__icontains=query) |
                    Q(slug__icontains=query) |
                    Q(description__icontains=query) |
                    Q(unit_discount_price__icontains=query)
                    )

        return self.filter(lookup)

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def search(self, query=None):
        if query is None:
            return self.get_queryset().none()
        return self.get_queryset().search(query)

class Product(models.Model):
    currencies = (
        ('₦','naira'),
        ('＄','dollars'))
    name = models.CharField(max_length = 100)
    description = models.TextField()
    slug = models.SlugField()
    sale_currency = models.CharField(max_length = 6, choices = currencies)
    unit_price = models.CharField(max_length = 10)
    unit_discount_price = models.CharField(max_length = 10)
    quantity_available = models.CharField(max_length = 10)
    product_category = models.ManyToManyField(Categorie)
    upload_timestamp = models.DateTimeField(auto_now_add = True)

    objects = ProductManager()

    def __str__(self):
        return self.name

    def update_quantity(self, quantity_sold):
        self.quantity_available = self.quantity_available - quantity_sold

class SlideProduct(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    advert_text = models.CharField(max_length = 100)
    upload_timestamp = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.product.name

class ProductPhoto(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    image = models.ImageField(upload_to = 'products/images')

    def __str__(self):
        return self.product.name

class Subscriber(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

class FAQ(models.Model):
    question = models.CharField(max_length = 200)
    answer = models.TextField()
    upload_timestamp = models.DateTimeField( auto_now_add = True)

    def __str__(self):
        return self.question

class AdditionalInformation(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    feature = models.CharField(max_length = 100)
    detail = models.CharField(max_length = 100)

    def __str__(self):
        return self.product.name

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    quantity = models.CharField(max_length = 10)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quantity} of {self.product.name}'

    def sub_total_price(self):
        total = int(self.product.unit_discount_price) * int(self.quantity)
        floattotal = float("{0:.2f}".format(total))
        return floattotal

class Client(models.Model):
    name = models.CharField(max_length = 100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

# Order Model
class Order(models.Model):
    orderitems  = models.ManyToManyField(Cart)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=200, blank=True , null=True)
    orderId = models.CharField(max_length=200, blank=True, null=True)
    
    def __str__(self):
        return self.user.username

    def total_price(self):
        total = 0
        for order_item in self.orderitems.all():
            total += order_item.sub_total_price()
        return total

class SearchQuery(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL)
    query = models.CharField(max_length=220)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.query

    class Meta:
        verbose_name_plural = "Search Queries"

class BillingAddress(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length = 20)
    lastname = models.CharField(max_length = 20)
    address = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=50)
    city = models.CharField(max_length=30)
    landmark = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.user.username} billing address'

    class Meta:
        verbose_name_plural = "Billing Addresses"


# Address Form
class BillingForm(ModelForm):

    class Meta:
        model = BillingAddress
        fields = ['firstname', 'lastname','address', 'zipcode', 'city', 'landmark']

blog/forms.py
from  django import forms
from django.forms import ModelForm
from blog.models import (Comment)


class CommentForm(ModelForm):
	class Meta:
		model = Comment
		fields = '__all__'
		widgets = {
			'article': forms.Select(attrs = {'id':'article',\
				'class':'stext-111 cl2 plh3 size-116 p-lr-18 invisible',\
				}),
			'name': forms.TextInput(attrs = {'id':'name',\
				'class':'stext-111 cl2 plh3 size-116 p-lr-18',\
				'placeholder':'Name *'}),
			'comment': forms.Textarea(attrs = {'id':'comment',\
				'class':'stext-111 cl2 plh3 size-124 p-lr-18 p-tb-15',\
				'placeholder':'Comment...',
				'rows':'4'}),
			'email': forms.EmailInput(attrs = {'id':'email',\
				'class':'stext-111 cl2 plh3 size-116 p-lr-18',
				'placeholder':'Email *'}),
			'website': forms.TextInput(attrs = {'id':'website',\
				'class':'stext-111 cl2 plh3 size-116 p-lr-18',
				'placeholder':'Website'})
		}

blog/templates/blog/blog-detail.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}{{ article.title }}{% endblock %}
{% block container %}
<br><br><br>
	<!-- breadcrumb -->
	<div class="container">
		<div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
			<a href="index.html" class="stext-109 cl8 hov-cl1 trans-04">
				Home
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>

			<a href="{% url 'blog:blog_index' %}" class="stext-109 cl8 hov-cl1 trans-04">
				Blog
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>

			<span class="stext-109 cl4">
				{{ article.title }}
			</span>
		</div>
	</div>


	<!-- Content page -->
	<section class="bg0 p-t-52 p-b-20">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-lg-9 p-b-80">
					<div class="p-r-45 p-r-0-lg">
						<!--  -->
						<div class="wrap-pic-w how-pos5-parent">
							<img src="/assets/{{ article.articleimage_set.all.0.image_file }}" alt="IMG-BLOG">

							<div class="flex-col-c-m size-123 bg9 how-pos5">
								<span class="ltext-107 cl2 txt-center">
									{{ article.upload_date | date:'d'}}
								</span>

								<span class="stext-109 cl3 txt-center">
									{{ article.upload_date | date:'M Y'}}
								</span>
							</div>
						</div>

						<div class="p-t-32">
							<span class="flex-w flex-m stext-111 cl2 p-b-19">
								<span>
									<span class="cl4">By</span> {{ article.author.name }} 
									<span class="cl12 m-l-4 m-r-6">|</span>
								</span>

								<span>
									{{ article.upload_date | date:'d M, Y' }}
									<span class="cl12 m-l-4 m-r-6">|</span>
								</span>

								<span>
									{% for category in article.categories.all %}{{ category.article_category }}, {% endfor%}
									<span class="cl12 m-l-4 m-r-6">|</span>
								</span>

								<span>
									{{ article.comment_set.all.count }} Comment{{ article.comment_set.all.count | pluralize }}
								</span>
							</span>
							<h4 class="ltext-109 cl2 p-b-28">
								{{ article.title }}
							</h4>
							{% for video in article.articlevideo_set.all %}
							<video controls="controls" class="video-fluid">
								<source src="/assets/{{ video.video_file }}" type="video/mp4" />
								Ops! Your browser does not support this video file
							</video>
							<h5 class="mtext-113 cl2 p-b-12">
								{{ video.caption }}
							</h5>
							{% endfor %}
							{% for text in article.articletext_set.all %}
							<h5 class="mtext-113 cl2 p-b-12">
								{{ text.header }}
							</h5>
							<p class="stext-117 cl6 p-b-26">{{ text.text }}</p>
							{% endfor %}
							{% for image in article.articleimage_set.all %}
							{% if forloop.counter == 1%}
							{% else %}
							<img src="/assets/{{ image.image_file }}" class="img-fluid">
							<h5 class="mtext-113 cl2 p-b-12">
								{{ image.caption }}
							</h5>
							{% endif %}
							{% endfor %}
							

						</div>


						<!--  -->
						<div class="p-t-40">
							<h5 class="mtext-113 cl2 p-b-12">
								Leave a Comment
							</h5>

							<p class="stext-107 cl6 p-b-40">
								Your email address will not be published. Required fields are marked *
							</p>

							<form method="POST" action="{% url 'blog:blog_comment' %}">
								{% csrf_token %}
								
								<div class="bor19 m-b-20">
									{{ comment_form.comment }}
								</div>

								<div class="bor19 size-218 m-b-20">
									{{ comment_form.name }}
								</div>

								<div class="bor19 size-218 m-b-20">
									{{ comment_form.email }}
								</div>

								<div class="bor19 size-218 m-b-30">
									{{ comment_form.website }}
								</div>

								<button class="flex-c-m stext-101 cl0 size-125 bg3 bor2 hov-btn3 p-lr-15 trans-04">
									Post Comment
								</button>
								<div class="bor19 m-b-20 invisible">
									{{ comment_form.article }}
								</div>
							</form>
						</div>
					</div>
				</div>

				<div class="col-md-4 col-lg-3 p-b-80">
					<div class="side-menu">
						<div class="bor17 of-hidden pos-relative">
							<input class="stext-103 cl2 plh4 size-116 p-l-28 p-r-55" type="text" name="search" placeholder="Search">

							<button class="flex-c-m size-122 ab-t-r fs-18 cl4 hov-cl1 trans-04">
								<i class="zmdi zmdi-search"></i>
							</button>
						</div>

						<div class="p-t-55">
							<h4 class="mtext-112 cl2 p-b-33">
								Article Categories
							</h4>

							<ul>
								{% for category in blog_categories %}
								<li class="bor18">
									<a href="{% url 'blog:blog_category' category=category.article_category %}" class="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4">
										{{ category.get_article_category_display }}
									</a>
								</li>
								{% endfor %}
							</ul>
						</div>

						<div class="p-t-65">
							<h4 class="mtext-112 cl2 p-b-33">
								Featured Products
							</h4>

							<ul>
								{% for product in article.featured_products.all %}
								<li class="flex-w flex-t p-b-30">
									<a href="{% url 'web:product_detail' slug=product.slug %}" class="wrao-pic-w size-214 hov-ovelay1 m-r-20">
										<img src="/assets/{{ product.productphoto_set.all.0.image }}" alt="PRODUCT" class="img-fluid">
									</a>

									<div class="size-215 flex-col-t p-t-8">
										<a href="{% url 'web:product_detail' slug=product.slug %}" class="stext-116 cl8 hov-cl1 trans-04">
											{{ product.name }}
										</a>

										<span class="stext-116 cl6 p-t-20">
											<del style="color: red;">{{ product.sale_currency }}{{ product.unit_price }}</del><span> {{ product.sale_currency }}{{ product.unit_discount_price }}</span>
										</span>
									</div>
								</li>
								{% endfor %}
							</ul>
						</div>

					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="container">
			<div class="p-t-7">
					<!-- Comments --><div><h3>{{ comments.count }} Comment{{ comments.count | pluralize }}</h3></div>
										{% for comment in comments %}
										<div class="flex-w flex-t p-b-20">
											<div class="size-207">
												<div class="flex-w flex-sb-m p-b-17">
													<span class="mtext-107 cl2 p-r-20">
														{{ comment.name }}
													</span>

													<span class=" cl1">
														<i>{{ comment.upload_timestamp |date:'d M, Y'}} at {{ comment.upload_timestamp |date:'g:i a'}}</i>
													</span>
												</div>

												<p class="stext-102 cl6">
													{{ comment.comment }}
												</p>
											</div>
										</div>
										{% endfor %}

				</div>
		</div>
	</section>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
	{% if form_status == 'success' %}
	setTimeout(swal('Success Message', "Your comment has been successfully posted. Thanks for your generosity", "success"), 500)
	{% endif %}
	{% if form_status == 'fail' %}
	setTimeout(swal('Error Message', "An error occured while trying to post your comment. Please try again\nWe dearly appologize for the incovenience", "danger"), 500)
	{% endif %}
</script>
{% endblock %}

blog/templates/blog/blog.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}{{ site_details.name }} | blog{% endblock %}
{% block container %}
	<!-- Title page -->
	<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url({% static 'blog/images/social-media-3758364_1920.jpg' %});">
		<h2 class="ltext-105 cl0 txt-center">
			{% if current_category %}Category: {{ current_category }}{% else %}Blog{% endif %}
		</h2>
	</section>	


	<!-- Content page -->
	<section class="bg0 p-t-62 p-b-60">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-lg-9 p-b-80">
					<div class="p-r-45 p-r-0-lg">
						<div class="infinite-container">
    						{% for article in articles %}
      					<div class="infinite-item">
      						<!-- item blog -->
						<div class="p-b-63">
							<a href="{% url 'blog:blog_article' slug=article.slug %}" class="hov-img0 how-pos5-parent">
								<img src="/assets/{{ article.articleimage_set.all.0.image_file }}" alt="IMG-BLOG">

								<div class="flex-col-c-m size-123 bg9 how-pos5">
									<span class="ltext-107 cl2 txt-center">
										{{ article.upload_date | date:'d'}}
									</span>

									<span class="stext-109 cl3 txt-center">
										{{ article.upload_date | date:'M Y'}}
									</span>
								</div>
							</a>

							<div class="p-t-32">
								<h4 class="p-b-15">
									<a href="{% url 'blog:blog_article' slug=article.slug %}" class="ltext-108 cl2 hov-cl1 trans-04">
										{{ article.title }}
									</a>
								</h4>

								<p class="stext-117 cl6 text-truncate">
									{{ article.articletext_set.all.0.text }}
								</p>

								<div class="flex-w flex-sb-m p-t-18">
									<span class="flex-w flex-m stext-111 cl2 p-r-30 m-tb-10">
										<span>
											<span class="cl4">By</span><a href="{% url 'users:profile' article.author.id %}"> {{ article.author.name }}  
											</a><span class="cl12 m-l-4 m-r-6">|</span>
										</span>

										<span>
											{% for category in article.categories.all %}{{ category.article_category }}, {% endfor %}
											<span class="cl12 m-l-4 m-r-6">|</span>
										</span>

										<span>
											{{ article.comment_set.all.count }} Comment{{ article.comment_set.all.count | pluralize}}
										</span>
									</span>

									<a href="{% url 'blog:blog_article' slug=article.slug %}" class="stext-101 cl2 hov-cl1 trans-04 m-tb-10">
										Continue Reading

										<i class="fa fa-long-arrow-right m-l-9"></i>
									</a>
								</div>
							</div>
						</div>
      					</div>
    						{% endfor %}
  						</div>

  						<div class="loading" style="display: none;">
    					Loading...
  						</div>
						

						<!-- Pagination -->
						{% if articles.has_next %}
    					<a class="infinite-more-link" href="?page={{ numbers.next_page_number }}">More</a>
  						{% endif %}
					</div>
				</div>

				<div class="col-md-4 col-lg-3 p-b-80">
					<div class="side-menu">
						<form action='/blog/search/'>
							<div class="bor17 of-hidden pos-relative">
								<input class="stext-103 cl2 plh4 size-116 p-l-28 p-r-55" type="text" name='q' placeholder="Search">

								<button class="flex-c-m size-122 ab-t-r fs-18 cl4 hov-cl1 trans-04">
									<i class="zmdi zmdi-search"></i>
								</button>
							</div>
						</form>
						<div class="p-t-55">
							<h4 class="mtext-112 cl2 p-b-33">
								Article Categories
							</h4>

							<ul>
								{% for category in blog_categories %}
								<li class="bor18">
									<a href="{% url 'blog:blog_category' category=category.article_category %}" class="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4">
										{{ category.get_article_category_display }}
									</a>
								</li>
								{% endfor %}
							</ul>
						</div>

					</div>
				</div>
			</div>
		</div>
	</section>	
{% endblock %}

{% block scripts %}
	  <script>
    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],
      onBeforePageLoad: function () {
        $('.loading').show();
      },
      onAfterPageLoad: function ($items) {
        $('.loading').hide();
      }
    });
  </script>

{% endblock %}