design_y/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from design_y import settings
import web.urls
import blog.urls
import users.urls
from web import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.Index.as_view(), name='landing-page'),
    path('admin/', admin.site.urls),
    path('site/', include(web.urls)),
    path('blog/', include(blog.urls)),
    path('users/', include(users.urls)),
    path('search/', views.search_view, name = 'search'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/reset_done.html'), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/reset_complete.html'), name='password_reset_complete'),
]



if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('edit/', views.edit, name='edit'),
]

web/urls.py
from django.urls import path
import web.views as views

app_name = 'web'
urlpatterns = [
    path('index/', views.Index.as_view(), name = 'web_index'),
    path('product/<slug:slug>', views.ProductDetail.as_view(), name = 'product_detail'),
    path('categories/<str:category>', views.CategoryView.as_view(), name = 'product_categories'),
    path('FAQ/', views.FAQView.as_view(), name = 'qa'),
    path('contact/', views.ContactView.as_view(), name = 'contact'),
    path('new_client/', views.Client.as_view(), name = 'new_client'),
    path('subscribe/', views.SubscribeView.as_view(), name = 'subscribe'),
    path('about/', views.AboutView.as_view(), name = 'about'),
    path('add_to_cart/',views.AddToCart.as_view(), name = 'add_2_cart'),
    path('view_cart_contents/',views.ViewCart.as_view(), name = 'view_cart'),
    path('update_cart/<slug:slug>',views.UpdateCart.as_view(), name = 'update_cart'),
    
    path('checkout/', views.checkout, name="checkout"),
    path('verify_transaction/<str:reference>', views.charge, name="charge"),
    path('my-orders/', views.oderView, name="oderView")
]

users/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils import timezone
from django.utils.text import slugify
from django.utils. translation import gettext_lazy as _
from PIL import Image
from django.core.files.storage import default_storage as storage

from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    #User model with granular control

    email = models.EmailField(_('email address'), unique=True)
    # first_name = models.CharField(_('first name'), max_length=20)
    username = models.CharField(_('username'), max_length=20, unique=True)
    slug = models.SlugField(default='slug')
    is_staff = models.BooleanField(_('staff'),default=False)
    is_active = models.BooleanField(_('active'),default=True)
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)
    last_login = models.DateTimeField(_('last login'), auto_now=True)
    avatar = models.ImageField(upload_to='avatars', default='default.jpg', blank=True, null=True)
    bio = models.TextField(_('Bio'), blank=True, null=True)
    social_handle = models.CharField(_('Twitter/Instagram handle'), max_length=15, blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    def __str__(self):
        # full_name = '%s %s' %(self.first_name, self.last_name)
        return self.username

    def get_email(self):
        return self.email

    def save(self, *args, **kwargs):
        self.slug = slugify(self.email)
        super(CustomUser, self).save()

        img = Image.open(self.avatar)

        if img.height > 514 or img.width > 534:
            output_size = (514, 534)
            img.thumbnail(output_size)
            # img.save(self.avatar.path)
            fh = storage.open(self.avatar.name, "w")
            picture_format = 'png'
            img.save(fh, picture_format)
            fh.close()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.db import transaction
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
   
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email', 'username')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'username', 'avatar', 'bio', 'social_handle',)

    @transaction.atomic
    def save(self, *args, **kwargs):
        user = super().save(commit=False)
        user.is_guest = True
        user.save()
        return user

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login
from django.views.generic import DetailView
from django.contrib.auth import get_user_model
from django.contrib import messages
from blog.models import Article
from .forms import CustomUserChangeForm
from .forms import CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from web.models import (SiteDetail, Categorie)
from web.forms import SubscribeForm
from blog.models import Categorie as BlogCategory

User = get_user_model()


def signup(request):
    if request.user.is_authenticated:
        return redirect('web:web_index')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(email=user.email, password=raw_password)
            # login(request, user)
            messages.success(request,f'Your account has been created, you\'re now able to log in.')
            return redirect('users:login')
    else:
        form = CustomUserCreationForm()
    context = {}
    context['form'] = form
    context['title'] = 'Sign-Up'
    context['subscribeform'] = SubscribeForm()
    context['blog_categories'] = BlogCategory.objects.all()
    context['site_details'] = SiteDetail.objects.get()
    context['categories'] = Categorie.objects.all()
    return render(request, 'users/signup.html', context)


class Profile(DetailView):
    model = User
    template_name = 'users/profile.html'
    context_object_name = 'object'
    slug_field = 'slug'
    slug_url_kwarg = 'user'
    query_pk_and_slug = True

    def get_queryset(self, **kwargs):
        return User.objects.get(pk=self.kwargs['pk'])

    def get_object(self, **kwargs):
        return User.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subscribeform'] = SubscribeForm()
        context['blog_categories'] = BlogCategory.objects.all()
        context['site_details'] = SiteDetail.objects.get()
        context['categories'] = Categorie.objects.all()
        # context['count'] = Article.objects.filter(publish=True, author=self.get_object()).count()
        # context['articles'] = Article.objects.filter(publish=True, author=self.get_object()).order_by('-date_posted')
        context['title'] = 'Profile'
        return context


@login_required
def edit(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, f'You acccount has been updated')
            return redirect('users:profile', pk=request.user.id)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {}
    context['form'] = form
    context['title'] = 'Edit Profile'
    context['subscribeform'] = SubscribeForm()
    context['blog_categories'] = BlogCategory.objects.all()
    context['site_details'] = SiteDetail.objects.get()
    context['categories'] = Categorie.objects.all()
    return render(request, 'users/update_profile.html', context)

users/templates/users/login.html
{% extends "web/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} Login {% endblock %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'users/css/sign_up.css' %}">
{% endblock %}
{% block container %}
<br><br>
    <main>
        <form id="login" method="POST" action="">
                {% csrf_token %}
                <legend>Login</legend>
                {{ form|crispy }}
                <div class="btn-submit">
                        <input type="submit" value="LOG IN" />
                </div>
                <div class="signin">
                  <p>DON'T HAVE AN ACCOUNT YET?</p>
                  <p>CLICK HERE TO <a href="{% url 'users:signup' %}" id="signuplink">SIGN UP</a></p>
                    <p>Forgot Password? <a href="{% url 'password_reset' %}" id="signuplink">Click here</a></p>
                </div>
        </form>
    </main>
{% endblock %}

users/templates/users/logout.html
{% extends "web/base.html" %}
{% block title %} Logout {% endblock %}
{% block container %}
<br><br>
    <div class="container">
        <h2>You have been logged out</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'users:login' %}">Log In Again</a>
            </small>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'web/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}{{ site_details.name }} | Profile {% endblock %}
{% block style %}
<link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
<link rel="stylesheet" type="text/css" href="{% static 'users/css/profile.css' %}">
{% endblock %}
{% block container %}
<br><br>
    <div class="user_profile d-flex justify-content-between">
        <div class="d-flex profile_card-right">
            {% if object.avatar %}
            <div class="profile_img_cover">
                <img src="{{ object.avatar.url }}" alt="">
            </div>
            {% endif %}
            <div class="ml-lg-4 ml-md-3 ml-sm-2 ml-1">
                <h6 class="profile_name">{{ object.username }}</h6>
                <p class="membership">Membership Since : <span>{{ object.date_joined }}</span></p>
                <p class="profile_details">Email: {{ object.email }}</p>
                {% if object.social_handle %}
                <p class="profile_details">Twitter: <a href="https://twitter.com/{{ object.social_handle }}" target="_blank">{{ object.social_handle }}</a></p>
                {% endif %}
                {% if object.bio %}
                 <p class="profile-details">Bio: {{ object.bio }}</p>
                {% endif%}
            </div>
        </div>
        {% if user == object %}
        <div>
            <a href="{% url 'users:edit' %}"><i class='bx bxs-cog'></i></a>
        </div>
        {% endif %}
    </div>
{% endblock %}

users/templates/users/reset.html
{% extends "web/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} Reset {% endblock %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'users/css/sign_up.css' %}">
{% endblock %}
{% block container %}
<br><br>
		<main>
       		<form id="signup" method="POST">
				{% csrf_token %}
         		<legend>FORGOT PASSWORD</legend>

          		{{ form }}

            	<div class="btn-submit">
            		<input type="submit" value="SUBMIT" />
            	</div>	
        	</form>
    	</main>
{% endblock %}

users/templates/users/reset_complete.html
{% extends "web/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} Reset Complete {% endblock %}
{% block container %}
<br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <div class="alert alert-info">
                    Your password has been set
                </div>
                <a href="{% url 'users:login' %}">Sign in here</a>
            </div>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

users/templates/users/reset_confirm.html
{% extends "web/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} Reset Confirm {% endblock %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'users/css/sign_up.css' %}">
{% endblock %}
{% block container %}
<br><br>
		<main>
       		<form id="signup" method="POST">
				{% csrf_token %}
         		<legend>RESET PASSWORD</legend>

          		{{ form }}

            	<div class="btn-submit">
            		<input type="submit" value="SUBMIT" />
            	</div>	
        	</form>
    	</main>
{% endblock %}

users/templates/users/reset_done.html
{% extends "web/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} Reset Done {% endblock %}
{% block container %}
<br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                <div class="alert alert-info">
                    An email has been sent with instructions to reset your password
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

users/templates/users/signup.html
{% extends "web/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}{{ site_details.name }} | Signup {% endblock %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'users/css/sign_up.css' %}">
{% endblock %}
{% block container %}
<br><br>
    <main>
        <form id="login" method="POST" action="">
            {% csrf_token %}
            <legend>Sign Up</legend>
                {{ form|crispy }}
            <div class="btn-submit">
                <input type="submit" value="SIGN UP" />
            </div>
            <span class="terms"
              >By registering, you accept our
              <a href="http://">terms and conditions</a>
            </span>
            <div class="signin">
              <p>ALREADY HAVE AN ACCOUNT?</p>
              <p>CLICK HERE TO <a href="{% url 'users:login' %}" id="signuplink">SIGN IN</a></p>
            </div>
        </form>
    </main>
{% endblock %}

users/templates/users/update_profile.html
{% extends 'web/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}{{ site_details.name }} | Update Profile {% endblock %}
{% block style %}
<link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
<link rel="stylesheet" type="text/css" href="{% static 'users/css/profile.css' %}">
{% endblock %}
{% block container %}
<br><br>
   <div class="user_profile d-flex justify-content-between">
        <div class="d-flex profile_card-right">
            <div class="profile_img_cover">
                <img src="{{ user.avatar.url }}" alt="">
            </div>
            <div class="ml-lg-4 ml-md-3 ml-sm-2 ml-1">
                <h6 class="profile_name">{{ user.username }}</h6>
                <p class="membership">Membership Since : <span>{{ user.date_joined }}</span></p>
                <p class="profile_details">Email: {{ user.email }}</p>
                {% if user.social_handle %}
                <p class="profile_details">Twitter: <a href="https://twitter.com/{{ user.social_handle }}" target="_blank">{{ user.social_handle }}</a></p>
                {% endif %}
                {% if user.bio %}
                 <p class="profile-details">Bio: {{ user.bio }}</p>
                {% endif%}
            </div>
        </div>
    </div>
       <div class="container-fluid">
        <div class="row">
            <div class="col"></div>
            <div class="col-md-8 col-sm-12">
                <form method="POST" action="" enctype="multipart/form-data" class="mt-5">
        <legend class="border-bottom mb-4">Edit Profile</legend>
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Save</button>
            </div>
        </form>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}