blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'
urlpatterns = [
    path('',Blog.as_view(), name = 'blog_index'),
    path('category/<str:category>',BlogArticleCategory.as_view(), name = 'blog_category'),
    path('article/<slug:slug>',BlogArticle.as_view(), name = 'blog_article'),
    path('comment/',Comment.as_view(), name = 'blog_comment'),
    path('search/',search_view, name = 'blog_search'),
    
]

design_y/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from design_y import settings
import web.urls
import blog.urls
import users.urls
from web import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.Index.as_view(), name='landing-page'),
    path('admin/', admin.site.urls),
    path('site/', include(web.urls)),
    path('blog/', include(blog.urls)),
    path('users/', include(users.urls)),
    path('search/', views.search_view, name = 'search'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/reset_done.html'), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/reset_complete.html'), name='password_reset_complete'),
]



if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
import web.views as views

app_name = 'web'
urlpatterns = [
    path('index/', views.Index.as_view(), name = 'web_index'),
    path('product/<slug:slug>', views.ProductDetail.as_view(), name = 'product_detail'),
    path('categories/<str:category>', views.CategoryView.as_view(), name = 'product_categories'),
    path('FAQ/', views.FAQView.as_view(), name = 'qa'),
    path('contact/', views.ContactView.as_view(), name = 'contact'),
    path('new_client/', views.Client.as_view(), name = 'new_client'),
    path('subscribe/', views.SubscribeView.as_view(), name = 'subscribe'),
    path('about/', views.AboutView.as_view(), name = 'about'),
    path('add_to_cart/',views.AddToCart.as_view(), name = 'add_2_cart'),
    path('view_cart_contents/',views.ViewCart.as_view(), name = 'view_cart'),
    path('update_cart/<slug:slug>',views.UpdateCart.as_view(), name = 'update_cart'),
    
    path('checkout/', views.checkout, name="checkout"),
    path('verify_transaction/<str:reference>', views.charge, name="charge"),
    path('my-orders/', views.oderView, name="oderView")
]

web/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings
from django.db.models import Q
from django.utils import timezone
from django.forms import ModelForm

# Get the user model
User = get_user_model()

# Create your models here.

class SiteDetail(models.Model):
    name = models.CharField(max_length = 100)
    logo = models.ImageField(upload_to = 'site_detail/images')
    favicon = models.ImageField(upload_to = 'site_detail/images')
    apple_icon = models.ImageField(upload_to = 'site_detail/images')
    address = models.TextField()
    site_email = models.EmailField()
    site_biography = models.TextField()
    site_mission = models.TextField()
    site_quote = models.TextField()
    site_quote_by = models.TextField()
    our_story_image = models.ImageField(upload_to = 'site_detail/images', blank = True)
    our_mission_image = models.ImageField(upload_to = 'site_detail/images', blank = True)

    def __str__(self):
        return self.name

class PhoneNumber(models.Model):
    name = models.CharField(max_length = 70)
    phone_number = models.CharField(max_length = 14)
    site = models.ForeignKey(SiteDetail, on_delete = models.CASCADE)

    def __str__(self):
        return self.name

class SiteSocial(models.Model):
    socials = (
        ('facebook','Facebook'),
        ('instagram','Instagram'),
        ('twitter','Twitter'),
        ('whatsapp','WhatsAap'))
    site = models.ForeignKey(SiteDetail, on_delete = models.CASCADE)
    social_media = models.CharField(max_length = 50, choices = socials)
    link = models.URLField()

    def __str__(self):
        return self.social_media

class Categorie(models.Model):
    name = models.CharField(max_length = 40)
    image = models.ImageField(upload_to = 'category/images')
    slug = models.SlugField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

class ProductQuerySet(models.QuerySet):

    def search(self, query):
        lookup = (
                    Q(name__icontains=query) |
                    Q(slug__icontains=query) |
                    Q(description__icontains=query) |
                    Q(unit_discount_price__icontains=query)
                    )

        return self.filter(lookup)

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def search(self, query=None):
        if query is None:
            return self.get_queryset().none()
        return self.get_queryset().search(query)

class Product(models.Model):
    currencies = (
        ('₦','naira'),
        ('＄','dollars'))
    name = models.CharField(max_length = 100)
    description = models.TextField()
    slug = models.SlugField()
    sale_currency = models.CharField(max_length = 6, choices = currencies)
    unit_price = models.CharField(max_length = 10)
    unit_discount_price = models.CharField(max_length = 10)
    quantity_available = models.CharField(max_length = 10)
    product_category = models.ManyToManyField(Categorie)
    upload_timestamp = models.DateTimeField(auto_now_add = True)

    objects = ProductManager()

    def __str__(self):
        return self.name

    def update_quantity(self, quantity_sold):
        self.quantity_available = self.quantity_available - quantity_sold

class SlideProduct(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    advert_text = models.CharField(max_length = 100)
    upload_timestamp = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.product.name

class ProductPhoto(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    image = models.ImageField(upload_to = 'products/images')

    def __str__(self):
        return self.product.name

class Subscriber(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

class FAQ(models.Model):
    question = models.CharField(max_length = 200)
    answer = models.TextField()
    upload_timestamp = models.DateTimeField( auto_now_add = True)

    def __str__(self):
        return self.question

class AdditionalInformation(models.Model):
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    feature = models.CharField(max_length = 100)
    detail = models.CharField(max_length = 100)

    def __str__(self):
        return self.product.name

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    quantity = models.CharField(max_length = 10)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quantity} of {self.product.name}'

    def sub_total_price(self):
        total = int(self.product.unit_discount_price) * int(self.quantity)
        floattotal = float("{0:.2f}".format(total))
        return floattotal

class Client(models.Model):
    name = models.CharField(max_length = 100)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

# Order Model
class Order(models.Model):
    orderitems  = models.ManyToManyField(Cart)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=200, blank=True , null=True)
    orderId = models.CharField(max_length=200, blank=True, null=True)
    
    def __str__(self):
        return self.user.username

    def total_price(self):
        total = 0
        for order_item in self.orderitems.all():
            total += order_item.sub_total_price()
        return total

class SearchQuery(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL)
    query = models.CharField(max_length=220)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.query

    class Meta:
        verbose_name_plural = "Search Queries"

class BillingAddress(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length = 20)
    lastname = models.CharField(max_length = 20)
    address = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=50)
    city = models.CharField(max_length=30)
    landmark = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.user.username} billing address'

    class Meta:
        verbose_name_plural = "Billing Addresses"


# Address Form
class BillingForm(ModelForm):

    class Meta:
        model = BillingAddress
        fields = ['firstname', 'lastname','address', 'zipcode', 'city', 'landmark']

blog/forms.py
from  django import forms
from django.forms import ModelForm
from blog.models import (Comment)


class CommentForm(ModelForm):
	class Meta:
		model = Comment
		fields = '__all__'
		widgets = {
			'article': forms.Select(attrs = {'id':'article',\
				'class':'stext-111 cl2 plh3 size-116 p-lr-18 invisible',\
				}),
			'name': forms.TextInput(attrs = {'id':'name',\
				'class':'stext-111 cl2 plh3 size-116 p-lr-18',\
				'placeholder':'Name *'}),
			'comment': forms.Textarea(attrs = {'id':'comment',\
				'class':'stext-111 cl2 plh3 size-124 p-lr-18 p-tb-15',\
				'placeholder':'Comment...',
				'rows':'4'}),
			'email': forms.EmailInput(attrs = {'id':'email',\
				'class':'stext-111 cl2 plh3 size-116 p-lr-18',
				'placeholder':'Email *'}),
			'website': forms.TextInput(attrs = {'id':'website',\
				'class':'stext-111 cl2 plh3 size-116 p-lr-18',
				'placeholder':'Website'})
		}

blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import View
from web.models import (SiteDetail, Categorie, Order, SearchQuery)
from web.forms import SubscribeForm
from web.views import auto_paginate
from blog.models import Article
from blog.models import Comment as Cmt
from blog.models import Categorie as BlogCategory
from blog.forms import CommentForm

# Create your views here.
class Blog(View):

    def get(self, request):
        context = {}
        articles_list = Article.objects.all().filter(
            publication_status  = 'publish').order_by('-upload_date')
        context['articles'] = auto_paginate(request=request,
            queryset = articles_list , paginate_by = 4)
        context['subscribeform'] = SubscribeForm()
        context['active_blog'] = True
        context['blog_categories'] = BlogCategory.objects.all()
        context['site_details'] = SiteDetail.objects.get()
        context['categories'] = Categorie.objects.all()
        try:
            order = Order.objects.filter(user=request.user, ordered=False)
            if order.exists():
                context['cart'] = order[0]
            else:
                context['cart'] = order
        except: 
            pass
        template = 'blog/blog.html'
        return render(request, template, context)

class BlogArticle(View):

    def get(self, request, ** kwargs):
        template = 'blog/blog-detail.html'
        context = {}
        default_article = Article.objects.get(slug = kwargs['slug'])
        default_value = {'article': default_article}
        try:
            context['form_status'] = kwargs['form_status']
        except:
            pass
        context['subscribeform'] = SubscribeForm()
        context['comment_form'] = CommentForm( initial = default_value)
        context['comments'] = Cmt.objects.filter(
            article = default_article).order_by('-upload_timestamp')
        context['active_blog'] = True
        context['article'] = Article.objects.get(slug = kwargs['slug'])
        context['site_details'] = SiteDetail.objects.get()
        context['blog_categories'] = BlogCategory.objects.all()
        try:
            order = Order.objects.filter(user=request.user, ordered=False)
            if order.exists():
                context['cart'] = order[0]
            else:
                context['cart'] = order
        except: 
            pass
        context['categories'] = Categorie.objects.all()
        return render(request, template, context)

class BlogArticleCategory(View):

    def get(self, request, ** kwargs):
        context = {}
        fetch_category = kwargs['category']
        fetch_category = BlogCategory.objects.get(article_category = fetch_category)
        articles_list = Article.objects.all().filter(
            publication_status  = 'publish', categories = fetch_category).order_by('-upload_date')
        context['articles'] = auto_paginate(request=request,
            queryset = articles_list , paginate_by = 4)
        context['subscribeform'] = SubscribeForm()
        context['site_details'] = SiteDetail.objects.get()
        context['current_category'] = fetch_category
        context['blog_categories'] = BlogCategory.objects.all()
        context['categories'] = Categorie.objects.all()
        try:
            order = Order.objects.filter(user=request.user, ordered=False)
            if order.exists():
                context['cart'] = order[0]
            else:
                context['cart'] = order
        except: 
            pass
        template = 'blog/blog.html'
        return render(request, template, context)

class Comment(View):

    def post(self, request):
        new_comment = CommentForm(request.POST)
        if(new_comment.is_valid()):
            new_comment.save()
            return BlogArticle().get(request,
             slug = new_comment.cleaned_data['article'].slug,
             form_status = 'success')
        else:
            return BlogArticle().get(request,
             slug = new_comment.cleaned_data['article'].slug,
             form_status = 'fail')

def search_view(request):
    query = request.GET.get('q', None)
    user = None
    context = {}
    try:
        order = Order.objects.filter(user=request.user, ordered=False)
        if order.exists():
            context['cart'] = order[0]
        else:
            context['cart'] = order
    except: 
        pass
    if request.user.is_authenticated:
        user = request.user
    context["query"] = query
    if query is not None:
        SearchQuery.objects.create(user=user, query=query)
        blog_list = Article.objects.search(query=query).filter(
            publication_status  = 'publish').order_by('-upload_date')
        context['blog_list'] = auto_paginate(request=request,
            queryset = blog_list , paginate_by = 4)
    context['subscribeform'] = SubscribeForm()
    context['site_details'] = SiteDetail.objects.get()
    context['blog_categories'] = BlogCategory.objects.all()
    context['categories'] = Categorie.objects.all()
    context['active_blog'] = True
    return render(request, 'blog/view.html',context)

web/templates/web/about.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}{{ site_details.name }} | about{% endblock %}
{% block container %}
	<!-- Title page -->
	<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url({% static 'web/images/abouts.jpg' %});">
		<h2 class="ltext-105 cl0 txt-center">
			About
		</h2>
	</section>	


	<!-- Content page -->
	<section class="bg0 p-t-75 p-b-120">
		<div class="container">
			<div class="row p-b-148">
				<div class="col-md-7 col-lg-8">
					<div class="p-t-7 p-r-85 p-r-15-lg p-r-0-md">
						<h3 class="mtext-111 cl2 p-b-16">
							Our Story
						</h3>

						<p class="stext-113 cl6 p-b-26">
							{{ site_details.site_biography}}
						</p>

						<p class="stext-113 cl6 p-b-26">
							Any questions? Let us know in {{ site_details.address }} or call us on {% for number in site_details.phonenumber_set.all %}{{ number.phone_number }}, {% endfor %}
						</p>
					</div>
				</div>

				<div class="col-11 col-md-5 col-lg-4 m-lr-auto">
					<div class="how-bor1 ">
						<div class="hov-img0">
							<img src="/assets/{{ site_details.our_story_image }}" alt="IMG">
						</div>
					</div>
				</div>
			</div>
			
			<div class="row">
				<div class="order-md-2 col-md-7 col-lg-8 p-b-30">
					<div class="p-t-7 p-l-85 p-l-15-lg p-l-0-md">
						<h3 class="mtext-111 cl2 p-b-16">
							Our Mission
						</h3>

						<p class="stext-113 cl6 p-b-26">
							{{ site_details.site_mission }}
						</p>

						<div class="bor16 p-l-29 p-b-9 m-t-22">
							<p class="stext-114 cl6 p-r-40 p-b-11">
								{{ site_details.site_quote }}
							</p>

							<span class="stext-111 cl8">
								- {{ site_details.site_quote_by }}
							</span>
						</div>
					</div>
				</div>

				<div class="order-md-1 col-11 col-md-5 col-lg-4 m-lr-auto p-b-30">
					<div class="how-bor2">
						<div class="hov-img0">
							<img src="/assets/{{ site_details.our_mission_image }}" alt="IMG">
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>	
{% endblock %}

web/templates/web/cart.html
<div class="header-cart-content flex-w js-pscroll">
<ul class="header-cart-wrapitem w-full">
					{% for item in cart.orderitems.all %}
					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="/assets/{{ item.product.productphoto_set.all.0.image }}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="{% url 'web:product_detail' slug=item.product.slug %}" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								{{ item.product.name }}
							</a>

							<span class="header-cart-item-info">
								{{ item.quantity }} x {{ item.product.sale_currency}}{{ item.product.unit_discount_price }}
							</span>
						</div>
					</li>
					{% endfor %}
				</ul>
				
				<div class="w-full">
					<div class="header-cart-total w-full p-tb-40">
						Total: ₦{{ cart.total_price}}
					</div>

					<div class="header-cart-buttons flex-w w-full">
						<a href="{% url 'web:view_cart' %}" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10">
							View Cart
						</a>

						<a href="/site/checkout/" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">
							Check Out
						</a>
					</div>
				</div>
			</div>

web/templates/web/details.html
{% extends 'web/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Check Out Details{% endblock %}



{% block container %}
<br><br><br><br>

  <!-- breadcrumb -->
  <div class="container">
    <div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
      <a href="{% url 'web:web_index' %}" class="stext-109 cl8 hov-cl1 trans-04">
        Home
        <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
      </a>

      <span class="stext-109 cl4">
        Check Out Details
      </span>
    </div>
  </div>
    

  <div class="container mt-5">
    <h2 class="mb-3">Shipping Address > <span class="text-muted">Checkout</span></h2>
    <div class="row">
      <div class="col-md-9">
       <div class="card mb-5" style="height: auto">
         <div class="card-body">
            <form method="POST">
            {% csrf_token %}

           {{ form | crispy}}
            <button type="submit" class="btn btn-primary float-right">Next</button>
            </form>
         </div>
       </div>
        {% if savedAddress %}
        <h4>Saved Address</h4>
        <div class="card mb-5" style="height: auto">
          <div class="card-body">
            <p><b>FirstName :</b> {{ savedAddress.firstname }}</p>
            <p><b>LastName :</b> {{ savedAddress.lastname }}</p>
            <p><b>Address :</b> {{ savedAddress.address }}</p>
            <p><b>City :</b> {{ savedAddress.city }}</p>
            <p><b>Zipcode :</b> {{ savedAddress.zipcode }}</p>
            <p><b>Landmark :</b> {{ savedAddress.landmark }}</p>
          </div>
          <div class="card-body">
            <button class="btn btn-primary float-right" type="submit" onclick="payWithPaystack()"> Pay </button>
          </div>
        </div>
        {% endif %}
      </div>
      <div class="col-md-3">
        <div class="card" style="height: auto">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              {% for item in order_items %}
              <li class="list-group-item">{{ item.product.name }} x {{ item.quantity }}</li>
              {% endfor %}
            </ul>
          </div>
             <div class="card-footer">
              <span class="float-left"><b>Order Total</b></span>
              <span class="float-right"><b>₦ {{ order_total | floatformat:2 }}</b></span>
            </div>
        </div>
      </div>
    </div>
  </div>

  <script src="https://js.paystack.co/v1/inline.js"></script> 
  <script> 
    function payWithPaystack() {
      var handler = PaystackPop.setup({
        key: '{{ key }}', // Replace with your public key
        email: '{{ email }}',
        amount: '{{ order_total }}' * 100, 
        currency: 'NGN', // Use GHS for Ghana Cedis or USD for US Dollars
        firstname: '{{ firstname }}',
        lastname: '{{ lastname }}',
        reference: '{{ id }}', // Replace with a reference you generated
        callback: function(response) {
          //this happens after the payment is completed successfully
          var reference = response.reference;
          alert('Payment complete! Reference: ' + reference);
          // Make an AJAX call to your server with the reference to verify the transaction
          var upload_url = '{% url "web:oderView" %}';

          $.ajax({
            url: '/site/verify_transaction/' + reference,
            method: 'GET',
            success: function (response) {
              var a = JSON.parse(response);
              // the transaction status is in response.data.status
              if (a['data']['status'] == "success"){
                alert('Thank you for your Orders');
                window.location.href = upload_url;
              }
            }
          });
        },
        onClose: function() {
          alert('Transaction was not completed, window closed.');
        },
      });
      handler.openIframe();
    }
  </script>

{% endblock %}    

web/templates/web/payment.html
{% extends 'web/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Payment{% endblock %}



{% block container %}
<br><br><br><br>

  <!-- breadcrumb -->
  <div class="container">
    <div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
      <a href="{% url 'web:web_index' %}" class="stext-109 cl8 hov-cl1 trans-04">
        Home
        <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
      </a>

      <span class="stext-109 cl4">
        Payment
      </span>
    </div>
  </div>
    
  <script src="https://js.paystack.co/v1/inline.js"></script>
  <script> 
      var paymentForm = document.getElementById('paymentForm');
      paymentForm.addEventListener('submit', payWithPaystack, false);
      function payWithPaystack(e) {
        e.preventDefault();
        var handler = PaystackPop.setup({
          key: '', // Replace with your public key
          email: document.getElementById('email-address').value,
          amount: document.getElementById('amount').value * 100, // the amount value is multiplied by 100 to convert to the lowest currency unit
          currency: 'NGN', // Use GHS for Ghana Cedis or USD for US Dollars
          firstname: document.getElementById('first-name').value,
          lastname: document.getElementById('last-name').value,
          // reference: 'YOUR_REFERENCE', // Replace with a reference you generated
          callback: function(response) {
            //this happens after the payment is completed successfully
            var reference = response.reference;
            alert('Payment complete! Reference: ' + reference);
            // Make an AJAX call to your server with the reference to verify the transaction
            var upload_url = '{% url "web:oderView" %}';
            $.ajax({
              url: '{% url "web:charge" reference=reference %}',
              method: 'GET',
              success: function (response) {
                // the transaction status is in response.data.status
                if (response.data.status == ''){
                  alert('Thank you for your Orders');
                  window.location.href = upload_url;
                }
              }
            });
          },
          onClose: function() {
            alert('Transaction was not completed, window closed.');
          },
        });
        handler.openIframe();
      }
    </script>

  

{% endblock %}    

web/templates/web/shopping-cart.html
{% extends 'web/base.html' %}
{% load static %}
{% block title %}Cart{% endblock %}



{% block container %}
<br><br><br><br>
<div class="container">
	<div class="alert alert-danger">To update the quantity of a product in your cart, click on the product from your cart, change the quatity from <i>1 the default</i> to the new desired quantity and add it to cart again. We dearly appologize for the inconvenience.</div>
</div>
	<!-- breadcrumb -->
	<div class="container">
		<div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
			<a href="{% url 'web:web_index' %}" class="stext-109 cl8 hov-cl1 trans-04">
				Home
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>

			<span class="stext-109 cl4">
				Shoping Cart
			</span>
		</div>
	</div>
		

	<!-- Shoping Cart -->
	<form class="bg0 p-t-75 p-b-85">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 col-xl-7 m-lr-auto m-b-50">
					<div class="m-l-25 m-r--38 m-lr-0-xl">
						<div class="wrap-table-shopping-cart">
							<table class="table-shopping-cart">
								<tr class="table_head">
									<th class="column-1">Product</th>
									<th class="column-2"></th>
									<th class="column-3">Price</th>
									<th class="column-4">Quantity</th>
									<th class="column-5">Total</th>
									<th class="column-6"></th>
								</tr>

								{% for item in cart.orderitems.all %}
								<tr class="table_row">
									<td class="column-1">
										<a href="{% url 'web:product_detail' slug=item.product.slug %}">
											<div class="how-itemcart1">
											<img src="/assets/{{ item.product.productphoto_set.all.0.image }}" alt="IMG">
										</div>
										</a>
									</td>
									<td class="column-2"><a href="{% url 'web:product_detail' slug=item.product.slug %}" class="cl1">{{ item.product.name }}</a></td>
									<td class="column-3">{{ item.product.sale_currency}}{{ item.product.unit_discount_price }}</td>
									<td class="column-4">{{ item.quantity }}</td>
									<td class="column-5">{{ item.product.sale_currency}}{{ item.sub_total_price }}</td>
									<td class="column-6"><a href='{% url "web:update_cart" slug=item.product.slug %}' class="flex-c-m stext-101 cl2 size-119 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10">
										Remove
									</a></td>
								</tr>
								{% endfor %}

								<tr class="table_row">
									<td class="column-1">
										Total
									</td>
									<td class="column-2">-</td>
									<td class="column-3">-</td>
									<td class="column-4">-</td>
									<td class="column-5">₦{{ cart.total_price| floatformat:2 }}</td>
								</tr>
							</table>
						</div>

						<div class="flex-w flex-sb-m bor15 p-t-18 p-b-15 p-lr-40 p-lr-15-sm">
							
							<div class="flex-w flex-m m-r-20 m-tb-5">
								<div class="flex-c-m stext-101 cl2 size-118 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-5">
									<a href="{% url 'web:web_index' %}" >Continue Shoping</a>
								</div>
							</div>
							{% if request.user.is_authenticated %}
							<a href='/site/checkout/' class="flex-c-m stext-101 cl2 size-119 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10">
								Proceed To Checkout
							</a>
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>
{% endblock %}		